######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 20:31:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += card.h deck.h
SOURCES += card.c deck.c main.c
