######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 14:51:31 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug
#QMAKE_CFLAGS_DEBUG += -DMEMPOOL

# Input
HEADERS += list.h
SOURCES += list.c main.c
