######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 20 16:54:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += poly.h
SOURCES += main.c poly.c
