######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 13 10:05:20 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
