######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 1 14:37:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
