######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 1 22:53:44 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
