######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 6 18:18:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
