######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 16 20:44:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
