######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 15 10:33:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += deque.h
SOURCES += deque.c main.c
