######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 25 15:35:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += btree.h
SOURCES += btree.cpp main.cpp
