######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 16 22:40:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += queue.h
SOURCES += main.c queue.c
