######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 28 21:01:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
