######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 21:07:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
