######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 27 09:26:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += btree.h
SOURCES += btree.cpp main.cpp
