######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 18:55:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
