######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 13 17:01:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += st.h
SOURCES += main.c st.c
