######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 30 22:41:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
