######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 16:21:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
