######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 1 11:36:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
