######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 20:09:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
