######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 6 23:42:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
