######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 16 17:02:48 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += alloc.h bst.h globvar.h type.h
SOURCES += alloc.c bst.c globvar.c main.c type.c
