######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 10 12:56:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glovar.h heap3.h type.h
SOURCES += glovar.c heap3.c main.c
