######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 13:12:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
