######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 25 22:33:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
HEADERS += digit.h
SOURCES += digit.c main.c
