######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 24 15:40:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rbt.h
SOURCES += main.c rbt.c
