######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 21:32:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
