######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 21 21:57:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
