######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 16 15:48:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += randlist.h
SOURCES += main.c randlist.c
