######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 6 19:35:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
