######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 23 11:52:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cxx
