######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 11 21:05:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pq.h
SOURCES += main.c pq.c
