######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 21:02:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += queue.h
SOURCES += main.c queue.c
CONFIG += debug
