######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 11:15:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
