######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 14 14:53:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += st.h
SOURCES += main.c st.c
