######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 6 11:30:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
