######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 21 16:19:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
