######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 19:30:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
