######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 14:38:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
