######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 12 21:50:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c

CONFIG -= debug
