######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 13 19:16:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += st.h
SOURCES += main.c st.c
