######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 6 20:57:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
