######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 28 22:35:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
SOURCES += main.c
