######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 11:19:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

# Input
SOURCES += main.c
