######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 23 10:20:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
