######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 13:22:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
