######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 8 13:41:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
