######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 26 10:12:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += btree.h
SOURCES += btree.c main.c
