######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 13:31:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
