######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 31 13:53:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
