######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 14 20:09:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
