######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 19:01:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
