######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 3 20:41:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += link.h
SOURCES += link.c main.c
