######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 8 19:20:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pq.h
SOURCES += main.c pq.c
