######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 12 20:50:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
