######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 20 21:14:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
