######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 6 21:28:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
