######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 23 21:23:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
