######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 9 22:24:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glovar.h heap.h qsort.h type.h util.h
SOURCES += glovar.c heap.c main.c qsort.c util.c
