######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 23 14:56:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
