######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 10 18:13:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pq.h
SOURCES += main.c pq.c
