######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 13:52:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
