######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 9 13:36:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pq.h
SOURCES += main.c pq.c
