######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 15:46:31 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
