######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 21:28:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
