######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 09:11:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
