######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 14:00:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
