######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 14 14:12:25 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
