######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 27 14:48:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
