######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 9 18:12:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
