######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 23 12:55:20 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bst.h
SOURCES += bst.c main.c
