######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 17 14:57:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += queue.h
SOURCES += main.c queue.c
CONFIG += debug
