######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 20 14:11:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bst.h
SOURCES += bst.c main.c
