######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 11:35:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
