######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 23 10:33:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
