######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 1 20:15:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
