######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 15 18:58:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += alloc.h bst.h globvar.h type.h
SOURCES += alloc.c bst.c globvar.c main.c type.c
