######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 3 16:26:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
