######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 7 14:33:44 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
