######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 20:51:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
