######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 10:35:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += point.h triangle.h
SOURCES += main.c point.c triangle.c
