######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 20:56:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
