######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 15 09:00:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += queue.h
SOURCES += main.c queue.c
