######################################################################
# Automatically generated by qmake (3.0) ?? 1? 4 20:36:34 2013
######################################################################

TEMPLATE = app
TARGET = 31
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
