######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 6 19:31:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
