######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 27 13:28:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
