######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 14 16:09:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stackArray.h stackList.h
SOURCES += main.c stackArray.c stackList.c
