######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 14 19:49:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
