######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 19 23:56:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bst.h
SOURCES += bst.c main.c
