######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 20 15:03:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.h stack.h
SOURCES += complex.c main.c stack.c
