######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 16 21:10:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stack.h
SOURCES += main.c stack.c
CONFIG += debug
