######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 5 15:03:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.c
