######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 19:57:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += node.h
SOURCES += main.c node.c
