######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 8 15:56:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pq.h
SOURCES += main.c pq.c
