######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 09:54:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += point.h
SOURCES += main.c point.c
