######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 19:51:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.h
SOURCES += complex.c main.c
