######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 11:31:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += list.h
SOURCES += list.c main.c
